### ISSUE TITLE
Terminal Integration

### ISSUE THREAD

**Issue by jfmoy** [jfmoy/Fraise#10]
A new feature I am thinking of implementing is an embedded terminal. This terminal would be directly embedded in the window so the document view would be splited in two vertically to allow the user to work on it while editing a file.

What do you think of this idea?

**Comment by nicolasvnr** [comment]
As I use Fraise as my default HTML editor, a terminal integration will not be usefull to me, but certainly for others programmers.

But I don't think it must be a priority.

**Comment by memmaker650** [comment]
It could be a very useful tip. But must be an option, for example push command+k to create to open the embebed terminal in the lower part of the Fraise window.

Could be a nice tip for v4.0

**Comment by sejef** [comment]
Nice to see Fraise/Smultron living back. A terminal integration would be very useful when editing sh scritps or Apache/Php conf files !

**Comment by jfmoy** [comment]
memmaker650> exactly, I was imagining a sliding panel in the bottom of Fraise. I will develop that for 4.0 I guess.
