### ISSUE TITLE
Problem with Show invisible chars

### ISSUE THREAD

**Issue by nicolasvnr** [jfmoy/Fraise#11]
Hi everybody,

When I use the command "Show invisible chars", sometimes all my text disapears, and I must scroll to see it again. Is it normal ?

**Comment by jfmoy** [comment]
I don't think it is normal :-) It never happened to me. I will try to repeat this bug.

**Comment by jfmoy** [comment]
Can you try to give me a scenario? I tried but can't reproduce it.

**Comment by nicolasvnr** [comment]
Hum, it's dificult to explain because it never happens all the time.

I will try to make a scenario.
