### ISSUE TITLE
Line numbers not aligned correctly on large files

### ISSUE THREAD

**Issue by morito** [jfmoy/Fraise#13]
When opening very large files (about 100 000 lines) the line numbers do not align with the corresponding lines. I mean for example if there is line no. 96000 then the line number is somewhere between line 95999 and 96000.

**Comment by mat128** [comment]
I'm getting the same problem with a file less than 2000 lines long (in my case rdesktop.c from rdesktop 1.6.0 source). However, when I go back to the top and re-scroll down, the lines get aligned and everything is fine. Edit: I'm on Fraise 3.7.3.

**Comment by memmaker650** [comment]
I think, could be a problem with margins. Big number's size is bigger than margin used to represent they.
