### ISSUE TITLE
Open a directory

### ISSUE THREAD

**Issue by jfmoy** [jfmoy/Fraise#16]
Allow the user to open a directory (ie. every files contained in this directory).

**Comment by memmaker650** [comment]
Yeah, good idea.

**Comment by nicolasvnr** [comment]
It's already possible. Go to Preferences, Open / Save, then Open category.

**Comment by jfmoy** [comment]
I had never noticed this option. I don't know why it is not activated by default (without the recursivity though).

I guess I still can be surprised. Thanks.
