### ISSUE TITLE
Roadmap of Fraise

### ISSUE THREAD

**Issue by memmaker650** [jfmoy/Fraise#17]
I think should be interesant have a roadmap for version future 4.0. Many people have ideas to improve Fraise, but I think we/jmoy must select only some of them to be in version 4.
This may focus jmoy's work and will five us an idea of Fraise's.

I think, jmoy only must release a new version when solve a bug and wait for version 4.0 to release a versión with new capabilities.

**Comment by jfmoy** [comment]
I agree and it is planned. A website for Fraise will arrive soon with a trac system (or an equivalent portal) to allow everyone to look at the roadmap and timeline and report bugs in a more convenient way.

This github is a temporary solution.

**Comment by jfmoy** [comment]
I am currently migrating the project to Assembla. I will keep this github page as a main mirror for a while but Issues section is going to be deactivated pretty soon.

The assembla tickets and milestones are going to be more convenient for me to define a roadmap of Fraise, and for you to declare and keep track of your feature request and bugs.

You can check Fraise's assembla page at: http://www.assembla.com/wiki/show/fraise
