### ISSUE TITLE
Fraise Website

### ISSUE THREAD

**Issue by jfmoy** [jfmoy/Fraise#19]
Hello guys,

Today I received a $15 donation and I want to invest this money in a website domain. A lot of domains are reserved or used, I was thinking about fraise-project.com or fraise-project.org or fraiseapp.com

Time to participate guys, what is your preference?

**Comment by memmaker650** [comment]
Could be appfraise.com ?? If not i prefer fraise-app.com

**Comment by torrance** [comment]
Of those, I prefer fraiseapp.com

**Comment by jfmoy** [comment]
fraiseapp is my favorite as well.

**Comment by styfle** [comment]
fraiseapp.com

**Comment by nicolasvnr** [comment]
In thought about fraise-for-mac but fraiseapp.com is simplier :)

**Comment by jfmoy** [comment]
I will buy it today. As I prefer fraiseapp.com and it seems you like it too, I will buy this one.
