### ISSUE TITLE
Printing with Syntax Coloring

### ISSUE THREAD

**Issue by jfmoy** [jfmoy/Fraise#2]
In original Smultron when you try to print something you obtain a black&white copy of the file content without any highlight feature. I think will be good when you try to print something launch a window to select Print with Highlight or without highlight.

Thanks jfmoy for your work.

**Comment by memmaker650** [comment]
Thanx for copy my suggestion

**Comment by Donal2** [comment]
Good idea !

**Comment by jfmoy** [comment]
As said on the Smultron page, the option exists already. You can choose to print with syntax coloration or not using the advanced settings in Printing panel (accessible through the Down arrow). I just tested and it works perfectly.

Though, the default for this option is to be activated.
