### ISSUE TITLE
icons in document selector are too big

### ISSUE THREAD

**Issue by tessus** [jfmoy/Fraise#21]
The icons next to the filename in the document selector are too big and therefore less documents fit in there without having to scroll up and down.
It would be nice to have the possibility to set the icon size and to turn off the icons in the selector.

**Comment by jfmoy** [comment]
You can select the size of the icon by moving the slide in the bottom but you can't turn off the icon display.

**Comment by tessus** [comment]
Thanks, I totally overlooked the slider at the bottom.
