### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by pheraph** [jfmoy/Fraise#25]
Hi,

I know the title isn't very good, but Fraise simply doesn't work on my system (10.6). When I run it, I see only the title bar (though "Create an empty file at launch" is enabled in the options). When I open a file nothing seems to happen (But I get an empty window with CMD+1). The statusbar shows a bunch of (null)-entries. And so does the Font-selector (I can't change the font, too.). I tried to completely remove and reinstall it (removing this files: http://dl.dropbox.com/u/1666541/temp/fraise_files.png), but without success.

This is a screenshot with the empty window and the (null)-errors:
http://dl.dropbox.com/u/1666541/temp/fraise_errors.png

This is an analysis of the Application:
http://dl.dropbox.com/u/1666541/temp/Analyse-Fraise.txt

HTH,
Raphael

**Comment by jfmoy** [comment]
Can you try to switch your system language in English and run it again?

**Comment by pheraph** [comment]
Switched the language to english, un- and reinstalled the app, but it didn't help. :-(

**Comment by jfmoy** [comment]
(null) values come from an impossibility of reading the parameters file located in Application Support/Preferences/ and it seems that you have deleted it properly. Can you delete every files related to Fraise (binary, archive, both plist in Library/Preferences and folder in Library/Application Support), download Fraise again from this website (don't use a custom icon as you seem to) and launch it again.

You can use a tool like appcleaner to be sure that the cleaning is well done.

If it still doesn't work, can you send to me your parameters files? The analyze doesn't really say anything so it is hard for me to know what is the exact problem.

**Comment by pheraph** [comment]
I uninstalled with AppCleaner and reinstalled (with a freshly downloaded archive), still the same symptoms. Here are the parameter files:

http://dl.dropbox.com/u/1666541/temp/Fraise3.fraise
http://dl.dropbox.com/u/1666541/temp/org.fraise.Fraise.plist

**Comment by memmaker650** [comment]
Please, try to do this other experiment.
Go to Peter Borg page and download Smultron, the beta version for Snow Leopard. And tell us if this version works for you.

**Comment by jfmoy** [comment]
Thank you memmaker650.

I am pretty curious to get the result of this experiment, because I really don't see the problem... Even the parameters files look correct.

**Comment by pheraph** [comment]
To complete the confusion Smultron 3.6 beta works fine (I wasn't aware of a SL beta as 3.5.1 works fine for me, too).

**Comment by memmaker650** [comment]
Which version of SL do you use ??? 10.6.2 or the latest 10.6.3 ?? It's so weird look you are the unique man you suffer this problem.

**Comment by memmaker650** [comment]
jfmoy. A little question?? Smultron & Fraise have a the hability to send error log to you or to Bugzilla ???

**Comment by pheraph** [comment]
It appeared with 10.6.2 and now with 10.6.3. That's totally odd.

**Comment by jfmoy** [comment]
No it doesn't have this hability for now.

It is really difficult for me to understand the problem as your parameter files are correct, and everything seem fine.
