### ISSUE TITLE
PLEASE DON'T USE THIS SECTION ANYMORE, GO TO THE FRAISE'S ASSEMBLA PAGE

### ISSUE THREAD

**Issue by jfmoy** [jfmoy/Fraise#29]
I'm currently migrating the project to Assembla. I will keep this github page as a main mirror for a while but Issues section is going to be deactivated pretty soon.

The assembla tickets and milestones are going to be more convenient for me to define a roadmap of Fraise, and for you to declare and keep track of your feature request and bugs. 

You can check Fraise's assembla page and add support tickets at: https://www.assembla.com/spaces/fraise/

**Comment by mat128** [comment]
As regular users (just registered), we can't post issues on the Assembla space for Fraise!

**Comment by jfmoy** [comment]
Fixed :-)
