### ISSUE TITLE
Notes & Commandes

### ISSUE THREAD

**Issue by Donal2** [jfmoy/Fraise#4]
Bonjour,
- Les "Notes" ne conservent pas les tabulations lors du passage à la ligne.
- les "Commandes" ne fonctionnent pas, notamment la convertion en HTML Entities où je suis obligé d'ajouter "usleep(100000);" pour que cela fonctionne.
  Merci et bon courage pour la suite !

**Comment by jfmoy** [comment]
English translation:
- Snippets don't keep tabulations after new line return.
- Some commands don't work, notably the HTML Entities conversion one for which I am obliged to add "usleep(100000);" to make it work.

Thanks and good luck.

**Comment by jfmoy** [comment]
- Snippets keep tabulations on my version.
- Effectively, the commands display the result for a too short period of time.

**Comment by nicolasvnr** [comment]
Snippets keep tabulations, but we can't cancel when we edit in snippets' textarea...
In addition, we can't remove snippets or collection of snippets.

Finally, it would be great if HTML Entities Conversion works (without convert chars < > of course if we select all HTML in a document), and if you add a keyboard shortcut to this function (as cmd + &). 
Now, when I use HTML Entities conversion, it removes all the text selected...

It would be nice also if the Snippets could be shown at the bottom left of Fraise's window, as in the editor named Espresso (but in this case it's at the bottom right).

@jfmoy : did you receive my mail ?

**Comment by jfmoy** [comment]
- You can remove a snippet or a collection by pressing "Del" or "Alt + Backspace" depending of your keyboard. I have to admit it is not convenient.
- You can assign yourself a shortcut to a snippet using the corresponding column in the Snippets window.
- HTML Entities conversion is buggy, as some other commands, I have to correct them.

**Comment by nicolasvnr** [comment]
I tried cmd + del in order to delete snippet, and I didn't try only Del. Thanks !

**Comment by jfmoy** [comment]
For all these things, I will rewrite the manual because I see that a lot of functionalities are unknown.

**Comment by jfmoy** [comment]
- I will add two buttons (one for deleting a collection, and the other to delete a command) to make it more easy to understand.
- For non-working commands, would be cool to analyze each of them and find better/working commands to include in Fraise.
