### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by Donal2** [jfmoy/Fraise#6]
(bad) Onglet Général -> Au lancement : Créer un nouveau doc

(good) Onglet Général -> Au lancement : Créer un nouveau document

(bad) Onglet Ouverture et enregistrement -> A l'enregistrement : Affecter le document à Smultron

(good) Onglet Ouverture et enregistrement -> A l'enregistrement : Affecter le document à Fraise

une idée pour la recherche rapide : la touche entrer et un clic sur la loupe devrait permettre de passer plus rapidement à l'occurrence suivante (à l'heure actuelle on est obligé de faire un cmd + g)

**Comment by jfmoy** [comment]
Corrected

**Comment by nicolasvnr** [comment]
I add :

(bad) Fichier > Enregistrer les document comme projet

(good) Fichier > Enregistrer les documents comme projet

**Comment by jfmoy** [comment]
Corrected.

Sorry guys, I know I am French and I should notice these errors but I use the English version almost exclusively :-)
