### ISSUE TITLE
Bug With Linenumber Prefs

### ISSUE THREAD

**Issue by axelGschaider** [jfmoy/Fraise#7]
Using Fraise 3.7.2 I can't alter the way the linenumbers are shown

(since I got the german localisation running I don't know the english or french pref entries but i guess you'll get the picture):
- switching the linenumbers on or off only affects new documents (Cmd-n) . The current one stays the same. When switching between the new and the old document also means switching between old and new pref.
- changing the width of the linenumber grid actually does nothing. The current and new documents stay unaffected. Reopening the prefs shows the new number of pixels. But quitting Fraise, restarting and opening the prefs shows the default pixel width (40 pixels).

**Comment by jfmoy** [comment]
For the first point, effectively the paramater is considered for new documents only, I am going to have a look on that.

For the second one, it might be a problem with the German localisation as I don't have the problem on English localisation nor French one. I am going to have a look as well.

**Comment by jfmoy** [comment]
I just checked and the German version works perfectly too. It saves my settings when I quit an relaunch Fraise and apply the new width to every new documents.

**Comment by axelGschaider** [comment]
Ok now I had a look at it again and it turned out, that the values ARE being stored . . . but only if one hits return after editing the pixel width.
Not to sure but right now I regard this as quite unusual (although I couldn't come up with an example) and counterintuitive. The fact, that I didn't even think about hitting return makes me guess that it is pretty common not to have to do so.

Anyway: can't call this a bug anymore (a strange interface behavior maybe...but then again: maybe it's just me)

Thx for all the work and the quick response times °thumbs up°

**Comment by jfmoy** [comment]
The only other solution is to put a button to validate or to listen to the text field value all the time but could be as settings are applied live, would be problematic for wrong value detection.

Also, you can't have both between settings applied without pressing Enter and an update on current opened documents as it would provoke a strange behaviour.

**Comment by axelGschaider** [comment]
I totally see your point there although I'd have to argue that it would be possible to listen to the NSControlTextDidChangeNotification, set the new value if A) the window is closed and B) the value is valid (if not just keep the old value). Additionally the value could be stored and updated when the user hits return within the field (although I don't know if NSControlTextDidChangeNotification reports that in an NSTextField).

On the other hand: that's quite a fuzz over something most users will use only once in a lifetime and then keep it. If it keeps disturbing me, maybe I'll just fork this repository one day and change it ;)

Once again: can't tell you how glad I am that my favorite editor is being developed again

**Comment by jfmoy** [comment]
I am actually working on it:

When the user will press Enter after modifying the width value, all opened documents will be updated to consider the new width. I still have a small issue but it is almost ready. I think it is a good compromise :-)

**Comment by jfmoy** [comment]
Done.

**Comment by axelGschaider** [comment]
cool. thank you. I'll make sure to download the source any time soon, so I can see it

**Comment by jfmoy** [comment]
The 3.7.3 version should be released this week end and should include this functionality.

**Comment by axelGschaider** [comment]
great! If only I was as quick as with producing new versions ;)
