### ISSUE TITLE
Text-only toolbar pops up icons when it should not

### ISSUE THREAD

**Issue by PhotonPanda** [jfmoy/Fraise#8]
If the toolbar is in text-only mode, pressing any of the items will pop up the icons. You then have to click the icon to do something. I believe this is the same behaviour as in Smultron but I don't recall if it has always been this way.

The expected behaviour is to function without popping up the icons for those items which have no 
text entry fields.

"Find" should be the only item to pop up the icons, since it has a text entry field. I'm not sure about the Functions, as it pops up a list. The remaining items should simply work when pressed.

**Comment by jfmoy** [comment]
Fixed
